# ===============================
# GENERAL CONFIG
# ===============================
spring.application.name=notification-service
server.port=8084
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# ===============================
# POSTGRES CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://order-db:5432/notification_db
spring.datasource.username=notification_user
spring.datasource.password=notification_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ===============================
# HEALTH CONFIG
# ===============================
management.endpoints.web.exposure.include=health,prometheus
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.server.port=8184
management.endpoint.health.group.readiness.include=kafka
management.endpoint.health.group.liveness.include=livenessState
management.metrics.tags.application=${spring.application.name}

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

# CONSUMER CONFIGS
# separate group to isolate from other services
spring.kafka.consumer.group-id=notification-group

# allow replaying all history
spring.kafka.consumer.auto-offset-reset=earliest

# key deserialization
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# tolerant error handling
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# JSON delegate
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# DO NOT require strict typing ? allow flexible message handling
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# accept all event types
spring.kafka.consumer.properties.spring.json.trusted.packages=*


# DO NOT fail if topics are missing
spring.kafka.listener.missing-topics-fatal=false

# processing per record keeps failure isolated
spring.kafka.listener.ack-mode=record

# DON'T crash application if broker is not available at startup
spring.kafka.admin.auto-create=false
spring.kafka.admin.fail-fast=false

app.kafka.topics.partitions=1
app.kafka.topics.replicas=1

# reduce Kafka noise
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.org.apache.kafka.clients.NetworkClient=ERROR
logging.level.o.a.k.c.c.internals=OFF

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=your-app-password
spring.mail.properties.mail.smtp.auth: true
spring.mail.properties.mail.smtp.starttls.enable: true




