# ===============================
# GENERAL CONFIG
# ===============================
spring.application.name=notification-service
server.port=8084
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# ===============================
# POSTGRES CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://order-db:5432/notification_db
spring.datasource.username=notification_user
spring.datasource.password=notification_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2