version: "3.9"

services:

  # KAFKA
  kafka:
    image: apache/kafka:4.0.2
    container_name: kafka
    environment:
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # TODO [FUTURE IMPROVEMENT] Add secure communication
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  # ORDER DB
  order-db:
    image: postgres:15
    container_name: order-db
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: order_user
      POSTGRES_PASSWORD: change-me
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U order_user -d order_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # ORDER DB
  order-db-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: order-db-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://order_user:change-me@order-db:5432/order_db?sslmode=disable"
    depends_on:
      order-db:
        condition: service_healthy


  # PAYMENT DB
  payment-db:
    image: postgres:15
    container_name: payment-db
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: change-me
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U payment_user -d payment_db" ]
      interval: 5s
      timeout: 5s
      retries: 5


  # PAYMENT DB EXPORTER
  payment-db-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: payment-db-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://payment_user:change-me@payment-db:5432/payment_db?sslmode=disable"
    depends_on:
      payment-db:
        condition: service_healthy

  # INVENTORY DB
  inventory-db:
    image: postgres:15
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: change-me
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U inventory_user -d inventory_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # INVENTORY DB EXPORTER
  inventory-db-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: inventory-db-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://inventory_user:change-me@inventory-db:5432/inventory_db?sslmode=disable"
    depends_on:
      inventory-db:
        condition: service_healthy

  # ORDER-SERVICE
  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile.dev
    container_name: order-service
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      order-db:
        condition: service_healthy
      kafka:
        condition: service_started

  # PAYMENT-SERVICE
  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile.dev
    container_name: payment-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      payment-db:
        condition: service_healthy
      kafka:
        condition: service_started

  # INVENTORY-SERVICE
  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile.dev
    container_name: inventory-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      inventory-db:
        condition: service_healthy
      kafka:
        condition: service_started

  # NOTIFICATION-SERVICE
  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile.dev
    container_name: notification-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092


  # PROMETHEUS
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./_observability/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - order-service
      - notification-service
      - inventory-service
      - payment-service

  # GRAFANA LOKI (Log Database)
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-storage:/loki

  # PROMTAIL
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./_observability/loki/promtail-config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

  # GRAFANA
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./_observability/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
      - loki

volumes:
  loki-storage:
  grafana-storage:
