apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: inventory-service
          image: inventory-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8183
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8183
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 3

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8183
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 3