apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
      kafka-client: "true"
  template:
    metadata:
      labels:
        app: notification-service
        kafka-client: "true"
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: notification-service
          image: notification-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8084
            - name: management
              containerPort: 8184

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true

          startupProbe:
            httpGet:
               path: /actuator/health/liveness
               port: management
            failureThreshold: 30
            periodSeconds: 10

          livenessProbe:
            httpGet:
               path: /actuator/health/liveness
               port: management
            initialDelaySeconds: 0
            periodSeconds: 10
            failureThreshold: 5

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 5

          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  key: KAFKA_BOOTSTRAP_SERVERS
                  name: notification-service-config

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: ClusterIP
  selector:
    app: notification-service
  ports:
    - port: 8084
      targetPort: http