package com.example.investigationservice.service.explanation.ai;

import com.example.investigationservice.model.AiExplanationResponse;
import com.example.investigationservice.model.InvestigationContext;
import com.example.investigationservice.service.explanation.ai.prompt.InvestigationPromptFactory;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.stereotype.Service;

import java.util.Optional;

/**
 * Primary AI explanation adapter used while no external model provider is configured.
 */
@Service
@ConditionalOnProperty(
        name = "app.ai.generator",
        havingValue = "mock",
        matchIfMissing = true
)
@Slf4j
public class MockAiExplanationGenerator implements AiExplanationGenerator {

    /** Provider identifier shared by mock execution and its tests. */
    public static final String PROVIDER = "mock";

    /** Versioned mock model identifier shared by execution and its tests. */
    public static final String MODEL = "mock-v1";

    @Override
    public String provider() {
        return PROVIDER;
    }

    @Override
    public String model() {
        return MODEL;
    }

    @Override
    public String promptVersion() {
        return InvestigationPromptFactory.PROMPT_VERSION;
    }

    /**
     * Returns a fixed explanation without calling an external provider.
     *
     * @param context authoritative evidence available for the order
     * @return hardcoded structured explanation candidate
     */
    @Override
    public Optional<AiExplanationResponse> generate(InvestigationContext context) {
        log.debug("[INVESTIGATION-SERVICE][MOCK-AI-EXPLANATION] Generating mock AI explanation for order {}", context.orderId());

        if (!context.hasEvidence()) {
            return Optional.empty();
        }

        var latestEvidence = context.evidence().getLast();
        return Optional.of(new AiExplanationResponse(
                "The order status was generated by the mock AI explanation provider.",
                context.currentStatus(),
                latestEvidence.reasonCode(),
                latestEvidence.decisionCode(),
                latestEvidence.compensationType()
        ));
    }
}
