spring.application.name=payment-service
server.port=8082

# ===============================
# POSTGRES CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://payment-db:5432/payment_db
spring.datasource.username=payment_user
spring.datasource.password=payment_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONNECTION POOL (IMPORTANT)
# ===============================
spring.datasource.hikari.connection-timeout=2000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ===============================
# LOGGING
# ===============================
logging.level.com.zaxxer.hikari=DEBUG

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

# Consumer basics
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer


# Error handling wrapper
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

# Delegate actual deserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

# Target type
spring.kafka.consumer.properties.spring.json.value.default.type=org.example.commons.event.PaymentRequestedEvent

# Trust packages (for JSON)
spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.kafka.listener.missing-topics-fatal=false
spring.kafka.listener.ack-mode=record

# 5 seconds timeout for producer API to reach Kafka
spring.kafka.producer.properties.max.block.ms=5000
# 5 seconds for broker response
spring.kafka.producer.properties.request.timeout.ms=5000
# 10 seconds timeout for the delivery (including retries, request time, backoff...)
spring.kafka.producer.properties.delivery.timeout.ms=10000
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true

# ===============================
# RESILIENCY
# ===============================
# look at last 10 calls to decide failure rate
resilience4j.circuitbreaker.instances.payment.slidingWindowSize=10
# 50% or more failures to open CB
resilience4j.circuitbreaker.instances.payment.failureRateThreshold=50
# wait 10 seconds before trying again
resilience4j.circuitbreaker.instances.payment.waitDurationInOpenState=10s
# allow 3 test calls to check if things are working
resilience4j.circuitbreaker.instances.payment.permittedNumberOfCallsInHalfOpenState=3

# allow 3 call attempts
resilience4j.retry.instances.payment.maxAttempts=3
# 0.5 seconds wait before each retry
resilience4j.retry.instances.payment.waitDuration=500ms
# Retry on these exceptions
resilience4j.retry.instances.payment.retryExceptions=\
java.io.IOException,\
java.net.ConnectException,\
java.net.SocketTimeoutException,\
java.util.concurrent.TimeoutException,\
org.springframework.web.client.ResourceAccessException,\
org.springframework.web.client.HttpServerErrorException, \
org.springframework.web.client.RestClientException

# Ignore these exceptions
resilience4j.retry.instances.payment.ignore-exceptions=\
org.springframework.web.client.HttpClientErrorException