apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - inventory_user
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: POSTGRES_DB
              value: inventory_db
            - name: POSTGRES_USER
              value: inventory_user
            - name: POSTGRES_PASSWORD
              value: inventory_pass

---

apiVersion: v1
kind: Service
metadata:
  name: inventory-db
spec:
  selector:
    app: inventory-db
  ports:
    - port: 5432
      targetPort: 5432
