apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-db
  template:
    metadata:
      labels:
        app: order-db
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - order_user
                - -d
                - order_db
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: order-service-config
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  key: DB_USERNAME
                  name: order-db-secret
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: order-db-secret
                  key: PASSWORD

---

apiVersion: v1
kind: Service
metadata:
  name: order-db
spec:
  type: ClusterIP
  selector:
    app: order-db
  ports:
    - port: 5432
      targetPort: 5432

