apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-db
  template:
    metadata:
      labels:
        app: payment-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432

          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - payment_user
                - -d
                - payment_db
            initialDelaySeconds: 5
            periodSeconds: 5

          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: DB_NAME
                  name: payment-service-config
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  key: DB_USERNAME
                  name: payment-service-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: payment-db-secret
                  key: password

---

apiVersion: v1
kind: Service
metadata:
  name: notification-db
spec:
  selector:
    app: notification-db
  ports:
    - port: 5432
      targetPort: 5432
