spring.application.name=order-service

# ===============================
# POSTGRES CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://order-db:5432/order_db
spring.datasource.username=order_user
spring.datasource.password=order_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2


# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.producer.acks=all
spring.kafka.producer.properties.enable.idempotence=true

spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true
app.kafka.topics.partitions=1
app.kafka.topics.replicas=1