spring.application.name=order-service

# ===============================
# H2 DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:h2:mem:orderingsystem
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Automatically create/update tables
spring.jpa.hibernate.ddl-auto=update

# ===============================
# H2 CONSOLE ENABLED
# ===============================
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Allow console access (important in Spring Boot 2.5+ / 3+)
spring.h2.console.settings.web-allow-others=true

# ===============================
# KAFKA
# ===============================
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.admin.auto-create=true
spring.kafka.admin.fail-fast=true
app.kafka.topics.partitions=1
app.kafka.topics.replicas=1

logging.level.org.apache.kafka= DEBUG
logging.level.org.springframework.kafk= DEBUG