# ===============================
# GENERAL CONFIG
# ===============================
spring.application.name=inventory-service
server.port=8083
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s

# ===============================
# POSTGRES CONFIG
# ===============================
spring.datasource.url=jdbc:postgresql://payment-db:5432/inventory_db
spring.datasource.username=inventory_user
spring.datasource.password=inventory_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# ===============================
# CONNECTION POOL
# ===============================
spring.datasource.hikari.connection-timeout=5000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

# ===============================
# HEALTH CONFIG
# ===============================
management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
management.server.port=8183
management.endpoint.health.group.readiness.include=db,kafka
management.endpoint.health.group.liveness.include=livenessState