package com.example.investigationservice.adapter.ai;

import com.example.investigationservice.model.InvestigationContext;
import com.example.investigationservice.port.out.AiExplanationGenerator;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Service;

import java.util.Optional;

/**
 * Primary AI explanation adapter used while no external model provider is configured.
 */
@Service
@Primary
@Slf4j
public class MockAiExplanationGenerator implements AiExplanationGenerator {

    private static final String MOCK_EXPLANATION =
            "The order status was generated by the mock AI explanation provider.";

    /**
     * Returns a fixed explanation without calling an external provider.
     *
     * @param context authoritative evidence available for the order
     * @return hardcoded mock explanation
     */
    @Override
    public Optional<String> generate(InvestigationContext context) {
        log.debug("[INVESTIGATION-SERVICE][MOCK-AI-EXPLANATION] Generating mock AI explanation for order {}", context.orderId());
        return Optional.of(MOCK_EXPLANATION);
    }
}
